import type { Metadata } from "next";
import { Zain } from "next/font/google";
import "./globals.css";
import { Menu } from "@/components/Menu";

const zain = Zain({
  variable: "--font-zain",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Solace Cafeteria",
  description: "landing page generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" />
      </head>
      <body className={` ${zain.variable} antialiased`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
